### PR TITLE
add some comments and jsdocs to ExportMap

### PR DESCRIPTION
**Pull request by soryy708**
`ExportMap` is difficult to follow, so lets add some helpful comments.

### CODE REVIEW

**Comment by soryy708** [comment]
I don't understand why `continuous-integration/appveyor/pr` failed.

```
Error: spawn nyc ENOENT
    at notFoundError (C:\projects\eslint-plugin-import\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\projects\eslint-plugin-import\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\projects\eslint-plugin-import\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\projects\eslint-plugin-import\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn nyc'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eslint-plugin-import@2.29.1 mocha: `cross-env BABEL_ENV=test nyc mocha "tests/src"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eslint-plugin-import@2.29.1 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Did it fail to find `nyc` installed?

**Comment by ljharb** [comment]
No need to worry about that; adding types to the util package seems to have broken appveyor.

**Comment by soryy708** [comment]
stale.

**Comment by ljharb** [comment]
That's fine, but let's reuse this PR rather than making a new one if a similar change comes up.

**Pull request closed without merging**
