### PR TITLE
⚠️ do not merge here, investigation only

### PR DESCRIPTION
**Pull request by AdriAt360**
investigation related to https://github.com/import-js/eslint-plugin-import/pull/2466#issuecomment-1146279811

### CODE REVIEW

**Comment by AdriAt360** [comment]
awesome, the test is broken here too, I can close
image

**Comment by ljharb** [comment]
Please don’t open throwaway PRs like this tho; a PR ref is a permanent mark on a repo that can’t ever be removed.

**Comment by AdriAt360** [comment]
@ljharb got it 👍🏽 
what's the preferred way of investigations needing to run the pipelines with unrelated changes to an existing PR?

**Comment by AdriAt360** [comment]
@ljharb it seems I can't reopen here after force pushing a new commit, are you able to with your admin rights by any chance?

**Comment by AdriAt360** [comment]
@ljharb note that I commented out the test on https://github.com/import-js/eslint-plugin-import/pull/2466 anyways, so we can just merge the other PR if it's ok for you, as it would be simpler
your call

**Pull request closed without merging**
