### PR TITLE
chore: try nvm to install node on wsl

### LINKED ISSUE #2737: WSL Error: Cannot find module 'semver'
All jobs with **WSL** config fail on `master`.
https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46338908

E.g.:
https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46338908/job/hqyre5h5sbfqqn44
````sh
Error: Cannot find module 'semver'
Require stack:
- /mnt/c/projects/eslint-plugin-import/tests/src/cli.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/index.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/tests/src/cli.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.replacementCompile (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.<computed> (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.replacementCompile (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.<computed> (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:152:7)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at runMain (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:68:10)
    at Function.<anonymous> (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:171:5)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at /home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:178:8
    at Object.<anonymous> (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:181:3)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/projects/eslint-plugin-import/tests/src/cli.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/index.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha'
  ]
}
````

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #2737 

Try to install node with [`nvm`](https://github.com/nvm-sh/nvm) as suggested here:
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm

### CODE REVIEW

**Comment by AndyOGo** [comment]
That didn't succeed...

https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46531151/job/suaoh4f063ydn60n#L34
```sh
wsl : Cloning into '/home/appveyor/.nvm'...
At line:1 char:1
+ wsl curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/master/inst ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into '/home/appveyor/.nvm'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by AndyOGo** [comment]
Fails again...

https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46533693/job/1kvv7b5dqps3kg5b#L33
```sh
bash: line 137: unexpected EOF while looking for matching `}'
bash: line 138: syntax error: unexpected end of file
Command exited with code 2
```

**Comment by ljharb** [comment]
(please keep reusing this PR for future attempts, rather than opening up a new one)

That particular failure indicates the script didn't download in its entirety.

**Comment by AndyOGo** [comment]
@ljharb I needed to pipe it through `dos2unix` 🤨 

I will try to `touch ~/.bash_profile` for the next error...

https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46535646/job/evt689nv4sdsfnw2#L77
```sh
=> Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zprofile, ~/.zshrc, and ~/.profile.
=> Create one of them and run this script again
   OR
=> Append the following lines to the correct file yourself:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
=> Close and reopen your terminal to start using nvm or run the following to use it now:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

**Comment by AndyOGo** [comment]
It installs `nvm`, but in a path which I can't access inside wsl.

https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46540082#L84
```sh
=> Downloading nvm from git to '/c/Users/appveyor/.nvm'
=> Cloning into 'C:/Users/appveyor/.nvm'...
```

https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46540082#L114
```sh
wsl ls -aR /c/Users/appveyor/
ls: cannot access '/c/Users/appveyor/': No such file or directory
Command exited with code 2
```

Honestly I never worked with WSL before and I'm sure there is some magic I don't know 😕 

Anyway nvm should be installed inside `$HOME` by default - but the path seem to resolve to different locations inside bash and wsl 😕 
https://github.com/nvm-sh/nvm/blob/edacf8275e3bef4a80971625ed89df13a9af427c/install.sh#L23-L25

**Comment by AndyOGo** [comment]
@ljharb 
Sorry, I give up.
I assumed it would be straight-forward to follow this guide to get node running inside WSL
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm

But man, was I wrong...
- [`ps:`](https://www.appveyor.com/docs/build-configuration/#interpreters-and-scripts) fails with `NativeCommandError` if a command outputs to `STDERR`
   - https://help.appveyor.com/discussions/problems/5413-calling-external-executable-causes-nativecommanderror-despite-no-apparent-error 
   - `curl -s` needs to be silenced
   - E.g `git clone 2>&1` outputs non-errors to `STDERR` and needs to be redirected - fore that reason I needed to fork [`nvm`](https://github.com/AndyOGo/nvm/tree/bugfix/powershell-git-clone-stderr)
- appveyor doesn't seem to support nodejs for WSL
   https://www.appveyor.com/docs/lang/nodejs-iojs/
- Actually that's all I can find about WSL on appveyor 🤨 
   - https://www.appveyor.com/blog/2019/10/11/vs2019-image-with-docker-wsl-preheated/#windows-subsystem-for-linux-wsl
   - https://www.appveyor.com/docs/windows-images-software/#wsl

**Pull request closed without merging**
