### PR TITLE
Fix eslints

### PR DESCRIPTION
**Pull request by OlivierZal**
@ljharb, to make tests more readable...

### CODE REVIEW

**Comment by ljharb** [comment]
is there anything enforcing this?

**Comment by OlivierZal** [comment]
Not really, I just read the test results from my other PR.

**Comment by ljharb** [comment]
These formatting changes should be enforced with eslint rules if we're going to make them en masse.

**Comment by OlivierZal** [comment]
I fixed all the warnings I saw there: https://github.com/import-js/eslint-plugin-import/actions/runs/6049563566/job/16417081560#step:4:1 (except the `no-console` one).

**Pull request closed without merging**
