### PR TITLE
Upgrade debug-dependency to 4.3.4

### LINKED ISSUE #2513: Upgrade debug dependency to 4.3.1+ or 3.2.7+
currently on 2.6.9 https://github.com/import-js/eslint-plugin-import/blob/0ef8cbaab5ba0789a6e1b716317b000b55ee4555/package.json#L104

but `npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)`

### PR DESCRIPTION
**Pull request by apupier**
fixes #2513

### CODE REVIEW

**Comment by apupier** [comment]
error in tests:
```
1) no-internal-modules invalid import get from "debug/node":

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1
      
      at testInvalidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:773:24)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:997:29)
      at processImmediate (node:internal/timers:471:21)

  2) no-internal-modules invalid export {get} from "debug/node":

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1
      
      at testInvalidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:773:24)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:997:29)
      at processImmediate (node:internal/timers:471:21)
```
i'm wondering if it is not that the updated dependency is no more breaking the rule and the test must be updated to use another package to test the rule. is it possible?

**Review by ljharb — CHANGES_REQUESTED** [review]
debug 4 requires node 6, which would be a breaking change and is a nonstarter

**Comment by apupier** [comment]
> requires node 6

Security support of Node 6 ended 3 years ago on the 30 Apr 2019 https://endoflife.date/nodejs
I wasn't imagining that it could be a constraint.
(but maybe supported by some companies and not the community?)
Are there documents on the policy for node version upgrade related to this project? (so that I can see how far we are from upgrading the minimal node version)

**Comment by ljharb** [comment]
We support down to eslint 2, and every version of node that implies. Platform support is, as always, irrelevant. We likely will not ever upgrade the minimal node version.

**Comment by JounQin** [comment]
See also #2447

**Pull request closed without merging**
