### PR TITLE
[utils] [fix] `parse`: remove unneeded extra backticks

### PR DESCRIPTION
**Pull request by G-Rath**
I won't admit how many times I'd read this warning while working on #2996 before I realised there were these (cosmetic) double backticks 😅

### CODE REVIEW

**Comment by ljharb** [comment]
They're intentional, to demarcate a JS property path versus prose words.

**Comment by G-Rath** [comment]
ah ok - that doesn't entirely surprise me, but is that a typical thing? I don't think I've ever seen double backquotes used, and meanwhile the sentence starts with a single backquote of a property which is why I decided to open the PR.

Either way no biggie, feel free to close if you want to keep it as is 🙂

**Comment by ljharb** [comment]
ohhh i get it, no, this is indeed just a typo :-) thanks, good catch

**Comment by G-Rath** [comment]
sorry I should have included an actual snippet or screenshot 😅

**Review by ljharb — APPROVED** [review]

**Pull request merged**
